{{- range $name, $config := .Values.microservices }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          # Динамически собираем имя образа
          image: "{{ $.Values.global.imageRegistry }}/{{ $name }}:{{ $.Values.global.imageTag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ $config.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes

            # Настройки базы данных (генерируются только если они указаны в values.yaml)
            {{- if $config.dbBouncer }}
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ $config.dbBouncer }}:5432/{{ $config.dbName }}"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_password
            {{- end }}

            # Общие секреты для всех Java-приложений
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt_secret
            - name: KAFKA_USER
              valueFrom:
                secretKeyRef:
                  name: kafka-secret
                  key: kafka_user
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secret
                  key: kafka_password

          # Выделение ресурсов
          resources:
            requests:
              memory: {{ $config.resources.requestMemory | quote }}
              cpu: "100m"
            limits:
              memory: {{ $config.resources.limitMemory | quote }}
              cpu: "500m"

          # Настройка проб готовности
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ $config.port }}
            initialDelaySeconds: 30
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ $config.port }}
            initialDelaySeconds: 60
            periodSeconds: 20
---
{{- end }}
