apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.dbSecret }}
  namespace: {{ include "todo-chart.namespace" . }}
type: Opaque
stringData:
  db_user: {{ .Values.secrets.db_user | quote }}
  db_password: {{ .Values.secrets.db_password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.jwtSecret }}
  namespace: {{ include "todo-chart.namespace" . }}
type: Opaque
stringData:
  jwt_secret: {{ .Values.secrets.jwt_secret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.kafkaSecret }}
  namespace: {{ include "todo-chart.namespace" . }}
type: Opaque
stringData:
  kafka_user: {{ .Values.secrets.kafka_user | quote }}
  kafka_password: {{ .Values.secrets.kafka_password | quote }}