{{- range $name, $config := .Values.microservices }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  # Для гейтвея делаем NodePort (чтобы открыть его наружу), для остальных - стандартный ClusterIP
  type: {{ if eq $name "api-gateway" }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
      - port: {{ $config.port }}
        targetPort: {{ $config.port }}
        name: http
    {{- if eq $name "api-gateway" }}
        nodePort: 32500
    {{- end }}
  selector:
    app: {{ $name }}
---
{{- end }}
